### ISSUE TITLE
hey i am dragovn we can update it ? :v

### ISSUE THREAD

**Issue by hachkingtohach1** [many1337/VillagerTradeAPI#6]
`public function onClick(PlayerInteractEvent $e){
		$p = $e->getPlayer();
		if($e->getAction() === PlayerInteractEvent::RIGHT_CLICK_BLOCK){
			$this->villagerId[$p->getName()] = $eid = mt_rand(0xfffff, 0x7fffffff);
			$pk = new AddActorPacket();
			$pk->entityRuntimeId = $eid;
			$pk->type = Villager::NETWORK_ID;
			$pk->position = $p->subtract(0, 4, 0);
			$pk->motion = new Vector3;
			$pk->yaw = $pk->pitch = 0;
			$pk->metadata = [
				Entity::DATA_FLAGS => [Entity::DATA_TYPE_LONG, 1 << Entity::DATA_FLAG_IMMOBILE],
				Entity::DATA_SCALE => [Entity::DATA_TYPE_FLOAT, 0]
			];
            $p->dataPacket($pk);//
			$tag = new CompoundTag("", []);
            $recipes = [[Item::get(Item::BRICK, 0, 1), Item::get(Item::SANDSTONE, 2, 2)], [Item::get(Item::BRICK, 0, 7), Item::get(Item::END_STONE, 0, 1)]];
            $this->recipes[$p->getName()] = $recipes;
            $result = [];
			$i = 0;
            foreach($recipes as $recipe){
                $array[$i] = $this->makeRecipe($recipe[0], $recipe[1], $recipe[2] ?? null);
				++$i;
            }
            $data = $tag->setTag(new ListTag("Recipes", $array));
            $nbt = new LittleEndianNBTStream();//			
            $tr = new UpdateTradePacket;
            $tr->windowId = 2;
            $tr->thisIsAlwaysZero = 0;
            $tr->tradeTier = 0;
            $tr->isWilling = false;
			$tr->isV2Trading = false;
            $tr->traderEid = $eid;
            $tr->playerEid = -1;
            $tr->displayName = "Shop";
            //$nbt = new LittleEndianNBTStream();//
            $tr->offers = $nbt->write($data);
			//$nbt->writeTag($wow);
            $p->dataPacket($tr);
		}
	}`

**Comment by hachkingtohach1** [comment]
this is beta

**Comment by Adam1609** [comment]
create a pull request. This is an issue tracker

**Comment by many1337** [comment]
I was updating this code. But I still have many things to innovate
half day- 2 days
